name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - name: RuboCop
      run: bundle exec rubocop
    - name: RSpec
      run: bundle exec rspec
      env:
        RBS_TEST_TARGET: "Koffer::*"
        RUBYOPT: "-rbundler/setup -rrbs/test/setup"
